#include "ReStructuredText.h"
#include <markup/Markup.h>
#include <cctype>
namespace markup::rst { namespace {
constexpr std::size_t max_input_bytes=64U*1024U*1024U;
std::string normalize(const std::string& input){std::string out;out.reserve(input.size());std::size_t column=0;for(std::size_t i=0;i<input.size();++i){unsigned char c=static_cast<unsigned char>(input[i]);if(!c){out+="\xef\xbf\xbd";column+=3;}else if(c=='\r'){out+='\n';column=0;if(i+1<input.size()&&input[i+1]=='\n')++i;}else if(c=='\n'){out+='\n';column=0;}else if(c=='\t'){std::size_t spaces=8-column%8;out.append(spaces,' ');column+=spaces;}else{out+=static_cast<char>(c);++column;}}return out;}
std::vector<std::string> lines_of(const std::string& input){std::vector<std::string> lines;std::size_t at=0;while(at<input.size()){auto end=input.find('\n',at);lines.push_back(input.substr(at,end==std::string::npos?std::string::npos:end-at));if(end==std::string::npos)break;at=end+1;}return lines;}
std::string escape(const std::string&s,bool attr=false){std::string o;for(char c:s)switch(c){case'&':o+="&amp;";break;case'<':o+="&lt;";break;case'>':o+="&gt;";break;case'"':o+=attr?"&quot;":"\"";break;default:o+=c;}return o;}
std::vector<Inline> parse_inlines(const std::string&text,Range source){std::vector<Inline>out;Inline plain;plain.source=source;auto flush=[&]{if(!plain.text.empty()){out.push_back(plain);plain.text.clear();}};for(std::size_t i=0;i<text.size();){if(text[i]=='\\'&&i+1<text.size()){plain.text+=text[i+1];i+=2;continue;}struct D{const char*m;InlineKind k;};static const D ds[]={{"**",InlineKind::Strong},{"``",InlineKind::Literal},{"*",InlineKind::Emphasis}};bool found=false;for(auto d:ds){std::string m=d.m;if(text.compare(i,m.size(),m))continue;auto e=text.find(m,i+m.size());if(e==std::string::npos||e==i+m.size())continue;flush();Inline n;n.kind=d.k;n.text=text.substr(i+m.size(),e-i-m.size());n.source=source;if(d.k!=InlineKind::Literal)n.children=parse_inlines(n.text,source);out.push_back(std::move(n));i=e+m.size();found=true;break;}if(found)continue;plain.text+=text[i++];}flush();return out;}
void parse_blocks(const std::vector<std::string>&lines,std::size_t&line,std::vector<Block>&blocks){while(line<lines.size()){while(line<lines.size()&&lines[line].empty())++line;if(line>=lines.size())break;std::size_t first=line;std::string text=lines[line++];while(line<lines.size()&&!lines[line].empty()){text+='\n';text+=lines[line++];}Block b;b.source.begin={first+1,1};b.source.end={line,lines[line-1].size()};b.text=text;b.inlines=parse_inlines(text,b.source);blocks.push_back(std::move(b));}}
std::string render_inlines(const std::vector<Inline>&nodes){std::string o;for(auto&n:nodes)switch(n.kind){case InlineKind::Text:o+=escape(n.text);break;case InlineKind::Emphasis:o+="<em>"+render_inlines(n.children)+"</em>";break;case InlineKind::Strong:o+="<strong>"+render_inlines(n.children)+"</strong>";break;case InlineKind::Literal:o+="<code>"+escape(n.text)+"</code>";break;default:o+=escape(n.text);}return o;}
std::string render_blocks(const std::vector<Block>&blocks){std::string o;for(auto&b:blocks)if(b.kind==BlockKind::Paragraph)o+="<p>"+render_inlines(b.inlines)+"</p>\n";return o;}
}
bool parse(const std::string&input,Document&doc,std::string&error,const Options&){doc={};error.clear();if(input.size()>max_input_bytes){error="reStructuredText input exceeds the 64 MiB library limit";return false;}auto normalized=normalize(input);auto lines=lines_of(normalized);std::size_t line=0;parse_blocks(lines,line,doc.blocks);if(!lines.empty()){doc.source.begin={1,1};doc.source.end={lines.size(),lines.back().size()};}return true;}
std::string render_html(const Document&doc,const Options&){return render_blocks(doc.blocks);}
}
